import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Opp={id:number,title:string,category:string,location:string,demand_volume:number,supply_capacity:number,score:number,missing_resources:string[]};
async function api(path:string,token:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(init.headers||{})}});if(!r.ok)throw new Error((await r.json()).detail||r.statusText);return r.json()}
function App(){const[token,setToken]=useState(localStorage.getItem('dw_token')||'');const[opps,setOpps]=useState<Opp[]>([]);const[stats,setStats]=useState<any>(null);const[msg,setMsg]=useState('');
 const load=async()=>{if(!token)return;try{setOpps(await api('/api/v1/opportunities',token));setStats(await api('/api/v1/dashboard',token))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[token]);
 const demoLogin=async()=>{try{const d=await api('/api/v1/auth/login','',{method:'POST',body:JSON.stringify({email:'owner@demandweave.local',password:'DemandWeave123!'})});localStorage.setItem('dw_token',d.access_token);setToken(d.access_token)}catch(e:any){setMsg('Run python scripts/seed_demo.py first. '+e.message)}};
 const compile=async()=>{await api('/api/v1/opportunities/compile',token,{method:'POST'});await load()};
 if(!token)return <main className="login"><section><span className="pill">Human Opportunity Compiler</span><h1>DemandWeave</h1><p>Turn weak economic signals into testable coalitions and bounded market experiments.</p><button onClick={demoLogin}>Open demo workspace</button><p className="error">{msg}</p></section></main>;
 return <main><header><div><b>DemandWeave</b><small>Opportunity operating system</small></div><nav><button onClick={compile}>Compile opportunities</button><button className="ghost" onClick={()=>{localStorage.clear();setToken('')}}>Sign out</button></nav></header><section className="hero"><div><span className="pill">PRE-MARKET FORMATION</span><h1>Find markets before they become marketplaces.</h1><p>Aggregate needs, idle capacity, skills, logistics and capital—without giving an agent unlimited authority.</p></div><div className="metric"><strong>{stats?.average_opportunity_score||0}</strong><span>average score</span></div></section><section className="stats">{stats&&Object.entries(stats).filter(([k])=>!['ledger','average_opportunity_score'].includes(k)).map(([k,v])=><article key={k}><b>{String(v)}</b><span>{k.replaceAll('_',' ')}</span></article>)}</section><section><div className="sectionTitle"><h2>Opportunity feed</h2><span>{opps.length} compiled</span></div><div className="grid">{opps.map(o=><article className="card" key={o.id}><div className="cardTop"><span className="pill">{o.category}</span><b>{o.score}</b></div><h3>{o.title}</h3><p>{o.location||'Multi-location'}</p><div className="bar"><i style={{width:`${o.score}%`}}/></div><dl><div><dt>Demand</dt><dd>{o.demand_volume.toLocaleString()}</dd></div><div><dt>Capacity</dt><dd>{o.supply_capacity.toLocaleString()}</dd></div></dl><small>Missing: {o.missing_resources.join(', ')||'none'}</small></article>)}</div>{!opps.length&&<div className="empty">Seed demo data, then compile opportunities.</div>}</section><footer>AI proposes · policy constrains · humans authorize · outcomes teach</footer></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
